
services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: node_app
    ports:
      - "80:80"
    depends_on:
      - pocketbase
    networks:
      - app-network

  pocketbase:
    build:
      context: ./pocketbase
      dockerfile: Dockerfile
    container_name: pocketbase
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
